Repository davmac314/dinit, pull requests merged in 2024-02, with the labels that each got.

#293 configure: Fix "parameter is not set" failure on setting "LDFLAGS_BASE"
  configure
Labels: Bug/Bugfix, A-Importance: Normal, Build-problem, make

#294 CI: Don't use matrix when there is no more than 1 task
  .cirrus.yml
Labels: Enhancement/New Feature, A-Importance: Low, CI

#299 Update CONTRIBUTORS
  CONTRIBUTORS
Labels: A-Importance: Low, C-misc
